# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HEIR-Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HEIR-Demo
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SkeletonView'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'CodableFirebase'

  target 'HEIR-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HEIR-DemoUITests' do
    # Pods for testing
  end

end
